// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved


[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "AdventureWorks.AWShopper.App", Justification="UnityContainer lifetime must match app lifetime. Cannot be disposed.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.ChangeVisualState.#GoToStateProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.CheckBoxCheckedToAction.#ActionProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.ComboBoxKeyboardSelection.#EnabledProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Controls.FormFieldTextBox.#WatermarkProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.HighlightFormComboOnErrors.#PropertyErrorsProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.HighlightFormFieldOnErrors.#PropertyErrorsProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.HighlightSearchBehavior.#SearchTermProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.HighlightSearchBehavior.#SearchTextProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.HighlightSearchBehavior.#HighlightBrushProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Behaviors.ListViewItemClickedToAction.#ActionProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "AdventureWorks.AWShopper.Common.DependencyPropertyChangedHelper.#HelperProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Justification= "Signing provided by app package.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "AdventureWorks.AWShopper.App", Justification = "Class is responsible for bootstrapping the rest of the application.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "AdventureWorks.AWShopper.App.#OnInitialize(Windows.ApplicationModel.Activation.IActivatedEventArgs)", Justification = "This method is responsible for bootstrapping the application.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "AdventureWorks.AWShopper.App.#OnInitialize(Windows.ApplicationModel.Activation.IActivatedEventArgs)", Justification = "The Unity Container manages lifetime of this object.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "AdventureWorks.AWShopper.Views.BillingAddressFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "AdventureWorks.AWShopper.Views.ChangeDefaultsFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "AdventureWorks.AWShopper.Views.PaymentMethodFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "AdventureWorks.AWShopper.Views.ShippingAddressFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "AdventureWorks.AWShopper.Views.SignInFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "AdventureWorks.AWShopper.Views.SignOutFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "AdventureWorks.AWShopper.Common.DependencyPropertyChangedHelper.#PropertyChanged", Justification = "The Windows.UI.XAML.DependencyPropertyChangedEventArgs is provided by the framework.")]
